#! /bin/sh
# Customized bspwmrc

## AUTOSTART ##
./.custom-picom.sh &
./.config/polybar/launch.sh & 

## MONITOR ##
bspc monitor -d I II III IV V VI

## BSPWM CONFIG
#bspc config border_radius         8
bspc config border_width          2
bspc config window_gap            2
bspc config top_padding           0
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

#### BSPWM coloring ####
bspc config normal_border_color         "#4c566a" #dark pastel blue
bspc config active_border_color         "#1e1e1e" #dark grey
bspc config focused_border_color        "#5e81ac" #light pastel blue
bspc config presel_feedback_color       "#5e81ac"
#bspc config urgent_border_color         "#dd2727" #bright pastel red

bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a 'VirtualBox Manager' desktop='^3'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

