#! /bin/sh
# CUSTOMIZED BSPWMRC

## Autostart ##
feh -z --bg-max '/home/manjar/Documents/Images/WP/' &
./.custom-picom.sh &
./.config/polybar/launch.sh & 
sudo loadkeys -d &
#nm-applet --indicator &
sxhkd &

## Monitor ##
bspc monitor -d I II III IV V VI

## Bsown Config ##
bspc config border_width          2
bspc config window_gap            2
bspc config top_padding           0
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

#### BSPWM coloring ####
bspc config normal_border_color         "#4c566a" #dark pastel blue
bspc config active_border_color         "#1e1e1e" #dark grey
bspc config focused_border_color        "#5e81ac" #light pastel blue
bspc config presel_feedback_color       "#5e81ac"
#"dd2727" #bright pastel red

bspc rule -a firefox desktop='^2'
bspc rule -a 'VirtualBox Manager' desktop='^3'
bspc rule -a Virt-manager desktop='^3'
bspc rule -a Ardour desktop='^4'
bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Nicotine desktop='^5' state=floating 
bspc rule -a ncmpcpp desktop='^6'

